[package]
name = "missed-connections"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
gtfs-realtime = "0.1.2"
gtfs-structures = "0.41.3"
prost = "0.13.3"
reqwest = { version = "0.12.8", features = ["blocking"] }
rusqlite = "0.32.1"


